### ISSUE TITLE
@Com Remove the multiple printStackTrace() for security reasons

### ISSUE THREAD

**Issue by AmauryMichel** [UTCAI12/onzzer-server#61]
There are printStackTrace() in ServerCommunicationController.java and ServerSocketManager.java that should be removed to prevent the user from seeing the error messages

**Comment by ValentinFagnet** [comment]
Issue fixed in PR #70

**Comment by ilianAZZ** [comment]
Fixed in https://github.com/UTCAI12/onzzer-server/pull/70
